### ISSUE TITLE
geodb update cron

### ISSUE THREAD

**Issue by rptaylor** [cvmfs-contrib/cvmfs-tutorial-2021#11]
docs/03_stratum1_proxies.md has a cron job to update the GeoDB . 

While you can do that if you want, it is automated by default so it is not necessary to have a cron job for that.
Pretty sure the automated updates come from doing snapshots so you get it for free on a s1, and not needed anyway on s0.

**Comment by bedroge** [comment]
Ah, you're right, the docs also mention that:
```
The cvmfs_server add-replica and snapshot commands will take care of automatically updating the database if you put a line like the following in /etc/cvmfs/server.local, replacing <license key> with the key you get from the signup process:

CVMFS_GEO_LICENSE_KEY=<license key>
```
Thanks, then we'll remove this.
