### ISSUE TITLE
CentOS 8 vs CentOS 7

### ISSUE THREAD

**Issue by boegel** [cvmfs-contrib/cvmfs-tutorial-2021#21]
We're currently providing commands for CentOS 8, but the cloud environment we will be using will provide CentOS 7, so we'll need to add back the installation of `epel-release`.

**Comment by bedroge** [comment]
Only needed for the server package (because of a dependency on `jq`), so the client doesn't need to install `epel-release`.

**Comment by boegel** [comment]
fixed in #36
