### ISSUE TITLE
create accounts in CycleCloud for attendees

### ISSUE THREAD

**Issue by boegel** [cvmfs-contrib/cvmfs-tutorial-2021#25]
Plan is to use anonymous accounts like `cvmfs001`, and send registered attendees an email with which account they can use.

Attendees will need to add their own SSH pubkey so they can log in to the instances.

**Comment by bedroge** [comment]
We should also tell them that only certain keys seem to work: `ed25519` doesn't work, `rsa` does.

**Comment by boegel** [comment]
@bedroge This can be closed?

Pubkey stuff is covered in #35

**Comment by bedroge** [comment]
Yep!
