### ISSUE TITLE
Recovering from situations with issues

### ISSUE THREAD

**Issue by bedroge** [cvmfs-contrib/cvmfs-tutorial-2021#3]
Axel asked about how one can remove a repo from the Stratum 1, as something went wrong and he wanted to redo some steps. It's probably good to explain `rmfs` and maybe some other useful commands/steps to recover from nasty situations, allowing people to redo certain steps. (maybe also an instruction for completely resetting their VM / reverting back to the original state/snapshot?)

**Comment by bedroge** [comment]
Added a note about removing a replica with `rmfs` here:
https://cvmfs-contrib.github.io/cvmfs-tutorial-2021/03_stratum1_proxies/#remove-the-replica

**Comment by rptaylor** [comment]
Aside from brute force rmfs, you can e.g. inspect  lock files in /var/spool/cvmfs/<repo>  and compare that with active processes to see what state a repo is in and determine which processes might need to be killed (or lock files cleaned up though I've never had to do that fortunately), but tread carefully if doing so.

`cvmfs_server list` is a useful quick way to check repo status .
