### ISSUE TITLE
Stratum 0 + client: add note about ip or hostname

### ISSUE THREAD

**Issue by rungitta** [cvmfs-contrib/cvmfs-tutorial-2021#4]
In the config section of 'Setting up a client' we should specify that the 'your-stratum0' part should be either the ip or hostname for the stratum0 server.

'CVMFS_SERVER_URL="http://your-stratum0/cvmfs/@fqrn@"

**Comment by boegel** [comment]
I'll tackle this while I go through the "Stratum 0 + client" (hopefully today)...

**Comment by boegel** [comment]
fixed in #6
