### ISSUE TITLE
apache log dir

### ISSUE THREAD

**Issue by rptaylor** [cvmfs-contrib/cvmfs-tutorial-2021#44]
In 05_advanced.md  it claims on CentOS the apache logs are in /var/log/apache2.
AFAIK the standard default location for httpd (apache) logs, at least in CentOS 6/7, is /var/log/httpd.
Is this from a non-standard httpd installation?

**Comment by bedroge** [comment]
Oops, yes, you're right :-)
Our EESSI Stratum 0 is running on Ubuntu, and I always mix it up which distro is using httpd/apache. I'll fix that, thanks!
