### ISSUE TITLE
Link to Ansible role?

### ISSUE THREAD

**Issue by bedroge** [cvmfs-contrib/cvmfs-tutorial-2021#5]
Perhaps we should add a warning somewhere that it may be better to automate the installation of the components (since it's quite easy to make mistakes when you do it manually), and insert a link to for instance the [Galaxy CVMFS Ansible role](https://github.com/galaxyproject/ansible-cvmfs).

**Comment by rptaylor** [comment]
https://git.computecanada.ca/cc-cvmfs-public/ansible-cvmfs-client  also available. I might move it to cvmfs-contrib at some point.

**Comment by boegel** [comment]
@bedroge This seems like a topic for a short section in the "Advanced" part?

I would point to the EESSI Ansible playbooks, and what ComputeCanada provides. A bit of self-promotion by the contributors to this tutorial shouldn't hurt. ;)
