### ISSUE TITLE
Using CVMFS in user space

### ISSUE THREAD

**Issue by casparvl** [cvmfs-contrib/cvmfs-tutorial-2021#50]
During the tutorial, I posted a question:

thinking about the tutorial yesterday, it described a lot of paths (for configs, the mountpoint of cvmfs) that are normally not available to end-users. Is it correct to assume there is no way (outside of using containers) to setup a CVMFS client in user space?

The answer was that https://github.com/cvmfs/cvmfsexec could be used, though mounting in another point than `/cvmfs/` could give a lot of issues - so you might still want to bind-mount into a container at `/cvmfs/` then.

The suggestion was that maybe this topic (setting up CVMFS completely in user space) could be another tutorial topic.

**Comment by DrDaveD** [comment]
Note that the cvmfsexec command (methods 2 & 3 of the package) already mounts at /cvmfs, in a user mount namespace.
